### PR TITLE
Use streamlined PHP FPM config.

### PR DESCRIPTION
**Pull request by orhtej2**
## Problem

- Full PHP FPM config.

## Solution

- Use auto generated one.

## PR Status

- [x] Code finished and ready to be reviewed/tested
- [ ] The fix/enhancement were manually tested (if applicable)

## Automatic tests

Automatic tests can be triggered on https://ci-apps-dev.yunohost.org/ *after creating the PR*, by commenting "!testme", "!gogogadgetoci" or "By the power of systemd, I invoke The Great App CI to test this Pull Request!". (N.B. : for this to work you need to be a member of the Yunohost-Apps organization)

### CODE REVIEW

**Comment by orhtej2** [comment]
!testme !bookwormtestme

**Comment by orhtej2** [comment]
Needs `config` support

**Comment by orhtej2** [comment]
Blocked by yunohost/issues#2268

**Comment by ericgaspar** [comment]
!testme

**Pull request closed without merging**
