### PR TITLE
Apply example_ynh

### PR DESCRIPTION
**Pull request by yalh76**
## Problem
- *Level 6*

## Solution
- *Apply example_ynh*

## PR Status
- [ ] Code finished.
- [ ] Tested with Package_check.
- [ ] Fix or enhancement tested.
- [ ] Upgrade from last version tested.
- [ ] Can be reviewed and tested.

## Validation
---
- [ ] **Code review** : 
- [ ] **Approval (LGTM)** :  
*Code review and approval have to be from a member of @YunoHost-Apps/apps-group*
- **CI succeeded** : 
[Build Status](https://ci-apps-hq.yunohost.org/jenkins/job/dotclear2_ynh%20PR-NUM-/)  
*Please replace '-NUM-' in this link by the PR number.*  
When the PR is marked as ready to merge, you have to wait for 3 days before really merging it.

### CODE REVIEW

**Comment by yalh76** [comment]
!testme

**Comment by kay0u** [comment]
Thank you :heart:

**Comment by yalh76** [comment]
!testme

**Comment by yalh76** [comment]
!testme

**Comment by yalh76** [comment]
!testme

**Review by alexAubin — APPROVED** [review]

**Comment by yalh76** [comment]
!testme

**Review by kay0u — APPROVED** [review]

**Pull request merged**
