### PR TITLE
Upgrade to 2.22~ynh1

### PR DESCRIPTION
**Pull request by kay0u**
## Solution

- *Upgrade to 2.22~ynh1*

## PR Status

- [x] Code finished and ready to be reviewed/tested
- [x] The fix/enhancement were manually tested (if applicable)

## Automatic tests

Automatic tests can be triggered on https://ci-apps-dev.yunohost.org/ *after creating the PR*, by commenting "!testme", "!gogogadgetoci" or "By the power of systemd, I invoke The Great App CI to test this Pull Request!". (N.B. : for this to work you need to be a member of the Yunohost-Apps organization)

### CODE REVIEW

**Comment by kay0u** [comment]
!testme

**Comment by yalh76** [comment]
!testme

**Comment by yalh76** [comment]
!bullseyetestme

**Comment by yalh76** [comment]
!bullseyetestme

**Comment by kay0u** [comment]
why do you want `.zip` and not `.tar.gz`?

**Comment by yalh76** [comment]
> why do you want `.zip` and not `.tar.gz`?

Because i wasn't able to manage the content of `.tar.gz` with the `.\`, seems like wrong formatted to me:


`.zip` content:
image



`.tar.gz` content:
image

**Comment by kay0u** [comment]
Weird, never had this problem, anyway, thank you for the update.

Waiting for bullseye before merging

**Pull request merged**
