### PR TITLE
Fix install not working

### PR DESCRIPTION
**Pull request by Mickael-Martin**
The config file of dotclear have been modified a bit.
I fix it and add type of variable on manifest.json

### CODE REVIEW

**Comment by rgarrigue** [comment]
Tried it in a debian 9, install's OK. PR accepted. Thanks @Mickael-Martin

**Comment by bourreP** [comment]
Hi, I'm sorry but I'm not allowed to accept this PR. Maybe @frju365 can do something for you :-)

**Comment by frju365** [comment]
I will merge it. @bourreP : do you accept to maintain this app. It's set as unmaintained, so if you want I add you as maintainer.

Same question for you, @rgarrigue

**Comment by frju365** [comment]
I forgot : @Mickael-Martin : do you want to create a team with @bourreP to maintain this awesome package and app ?

**Comment by bourreP** [comment]
Well it's ok for me but I don't know this app... For now...

**Comment by Mickael-Martin** [comment]
OK for me. @bourreP it's just a small CMS make by french guys. I use it since many years. Dotclear is a great project, simple but great.

**Comment by rgarrigue** [comment]
@frju365 : I don't mind being in the maintainers teams, sortof logical since I was the creator of yunohost's scripts for this one. But I don't have much time nowadays, best I can do is testing the install after a PR to avoid the "work on my machine (tm)" pitfall.

**Pull request merged**
